name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org/'
          scope: '@mdrv'
      - run: bun i # install
      - run: bun g # generate
      - run: bun b # build
      - name: Remove GitHub alerts from README.md for NPM
        run: sed -i -r '/^>\s+\[!\w+\]/d' ./README.md # 
      - name: 'Use `exports` from publishConfig'
        run: |
          jq \
            'reduce .publishConfig as $in (.; . + $in) | del(.publishConfig)' \
            package.json > package.json~
          mv package.json~ package.json
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org/'
          scope: '@mdrv'
      - name: 'Publish to NPM: `wbh`'
        run: npm publish --provenance --access public
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: 'Rename package with longer alias: `@mdrv/wbh`'
        # run: sed -i -r "$COMMAND" package.json
        # env:
        #   COMMAND: 's/"name": "wbh"/"name": "@mdrv\/wbh"/'
        run: |
          jq \
            '.name|="@mdrv/wbh"' \
            package.json > package.json~
          mv package.json~ package.json
      - name: Sleep for 10 seconds (to prevent E409 Conflict)
        run: sleep 10s
        shell: bash
      - name: 'Publish to NPM: `@mdrv/wbh`'
        run: npm publish --provenance --access public
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
